### ISSUE TITLE
Create docHandle from existing UUID

### ISSUE THREAD

**Issue by eberberich** [automerge/automerge-repo#381]
We (like to) use automerge as addition to an already centrally DB-stored document- and that document has a UUID. 

Would it be possible to add a second parameter ``uuid`` to 

``create<T>(initialValue?: T): DocHandle<T> {...}`` 

and when given, then instead of calling 

``const { documentId } = parseAutomergeUrl(generateAutomergeUrl())``

it would call

``const { documentId } = createAutomergeUrlFromUuid(uuid)``

We can assume that ``uuid`` is a UUID - and it can be checked by the repo code.

Or is there some rationale why you need to rely on your own generated UUID and not on externally generated UUIDs?

With the current setup we need to maintain another map to match automergeUrls to our own UUIDs

**Comment by pvh** [comment]
Hey! I get this question every once in a while. The short answer is that we deliberately do not support this because it created heaps of difficult-to-solve problems for people in the past related to ID reuse. I would recommend you record the automerge URL as a synthetic foreign key instead -- this gives you more flexibility in the event that you want to replace a document and protects you against a future where we change the ID format for whatever reason.

All this said, I totally understand the desire, and it's something we'll continue to consider as we work on the system... just probably not exactly in this way.

**Comment by eberberich** [comment]
@pvh thanks for the details! Was only searching open issues and couldn't find - maybe you can add some comment into the code (and the README) that explains that the ID will always be determined by automerge, and also the explanation you wrote - then - at least I- would not have opened this issue in the first place ;-)
