### ISSUE TITLE
Document corruption when updating while the dev server is stopped

### ISSUE THREAD

**Issue by ecstatic-morse** [automerge/automerge-repo#60]
While running the counter demo on the latest `main`, I found that starting (`yarn workspace automerge-repo-demo-counter dev`) and stopping (ctrl-c) the dev server a few times while incrementing the counter in the browser causes the saved document (the one in `localforage`) to become corrupted[^1]:

[^1]: It happens pretty consistently, but it's hard to give a specific set of actions. Maybe I'll record a screencast to make it easier for you to reproduce.

```
caught (in promise) error inflating document chunk ops: invalid changes: changes out of order
Repo.js:36
```

This persists across reloads (obviously), and only stops once you clear the IndexedDb (where localforage keeps data). I've attached a log containing the `localforage::keyvaluepairs` database (with `Uint8Array`s encoded to hex).

[localhost-1682658343400.log](https://github.com/automerge/automerge-repo/files/11350138/localhost-1682658343400.log)

Ultimately, this leaves the retrieved document handle in the loading state and causes the following error when you click the button and try to update the state:

```
Handle.js:170 Uncaught (in promise) Error: Cannot change while loading
    at DocHandle.change (DocHandle.js:170:19)
    at changeDoc (useDocument.js:21:16)
    at onClick (App.tsx:14:9)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
```

Besides fixing the underlying data corruption, it would be nice to surface this error earlier, preferably in `Repo.find`, but probably the best you can do is add an `error` event to `DocHandle`. Otherwise there's no way of knowing that loading the document failed besides listening to the `'error'` event on `window`.

**Comment by acurrieclark** [comment]
I am fairly certain that this issue won't be there if you use Automerge `2.0.3`. Would you mind updating and trying again?

Incidentally, the underlying issue is one I am looking into anyway. Currently, when a page is reloaded, the document is loaded from storage in increments. However, it looks as though (certainly in Automerge `<2.0.3`) the next incremental save always saves the whole document again, rather than just the previous change. When an attempt is made to reload again, the increments now include some of the changes twice, which causes the corruption.

I agree that it would be good to surface an error state somewhere within repo. Will have a think.

Let me know how you get on with 2.0.3 and we will go from there.

**Comment by ecstatic-morse** [comment]
I can no longer reproduce after upgrading to `2.0.3`. I'll close this for now, since the error handling thing is orthogonal. Thank you!
