### ISSUE TITLE
Device IDs

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge-repo#89]
Peter mentioned the idea of having some sort of `RepoId` which would be able to identify a device, and may contain multiple peers.

If this is achievable, a few thoughts on where it might help. The first 3 which spring to mind are:

1. Sync confidence - knowing that your data has successfully synced with another device
2. Local saves - the issue of multiple local peers (eg. open tabs) writing to the same data source could be trivially solved if local changes are only written by the peer which makes them. This doesn't help with who should write changes from the network, but it's a start.
3. Undo/Redo - Not yet part of Repo, and obviously a more complex topic, but at the very least you need a way to determine which changes have come from your own device and which have come from the rest of the network. What to do with that information is a conversation for another day.

Whatever the weather, I think being able to group and identify a cluster of `Repo`s would be most useful.

**Comment by acurrieclark** [comment]
Some initial thoughts on how this might work:

- ID is set within repo, and stored under a common ID in whichever storage adapter is attached
- Each time the Repo is initialised, it checks storage for an existing ID and creates a new one if absent
- Can be overridden by passing in a `DeviceId`/`RepoId` to the Repo constructor; useful if you have a local Repo instance which is not connected to storage, for example.

**Comment by pvh** [comment]
This seems very sensible; we can also keep track of sync states with the tuple repoId/docId/syncState.

Note that some peers may not be persistent. Browser tabs have their own local sync state but don't store anything in localstorage. We should be careful not to clutter up storage with the state of ephemeral peers.

**Comment by ept** [comment]
Perhaps relatedly, @orionz in automerge/automerge#617 added a kind of "branch ID" concept, which is an actorId extended with an integer to allow several branches to exist side-by-side. Seems like having multiple peers for a single device is a similar idea?

**Comment by pvh** [comment]
Interesting! I think we can't do quite the same thing without some kind of leader mechanism (and solving the attendant problems that follow)... My gut reaction is that a "peer" in our current terminology should converge to become a "repo", which is to say a stored (or ephemeral) instance of some documents. Peers should include a hint about whether they plan to return during handshaking. 

This is a bit of a puzzle... in the case of blutack, where we have messages run from tab -> shared_worker -> sync_server -> shared_worker -> tab, I suppose the "sync state" from an application perspective is whether the shared_worker is in sync with the server, and the "peer state" is the sync state from the other party's shared_worker. Tabs should panic any time they fall out of sync with the shared_worker and otherwise be treated as disposable.

In this case, I believe only the shared_worker's repo, stored in localStorage is really important.

**Comment by acurrieclark** [comment]
@pvh @alexjg @paulsonnentag I think that this idea has largely been superseded by the addition of `StorageId`. Happy for me to close this, or does it offer anything else?

**Comment by alexjg** [comment]
Agreed, closing.
